### ISSUE TITLE
dayView not showing correct day

### ISSUE THREAD

**Issue by w-veltman** [Jamaks/ng-fullcalendar#100]
Hello,

First of all, a really nice calendar you've made.

But, when I dos the following steps the dayView does not show the correct day in day-header:

1. go to dayView (shows the correct day)
2. click next/prev button (keeps showing the correct day)
3. click on weekView/monthView (all fine as well)
4. click on dayView again (doesn't show the correct day of week)

I have the following code to accomplish the functions:

import { Component, OnInit, ViewChild, Input } from '@angular/core';
import { CalendarComponent } from 'ng-fullcalendar';
import { Options } from 'fullcalendar';
import * as $ from 'jquery';
import 'fullcalendar';

@Component({
  selector: 'go-scheduler',
  templateUrl: './scheduler.component.html',
  styleUrls: ['./scheduler.component.scss']
})

export class SchedulerComponent implements OnInit {

  @Input() data: any[] = [];

  public listviewShown: boolean;

  public calendarOptions: Options;
  @ViewChild(CalendarComponent) ucCalendar: CalendarComponent;

  public title: string;
  private currentDate = moment().locale('nl').format('YYYY-MM-DD');
  private today = moment().locale('nl');

  constructor() { }

  ngOnInit() {
    this.title = moment(this.currentDate).locale('nl').format('MMMM YYYY');
    this.calendarOptions = {
      editable: true,
      eventLimit: false,
      buttonText: {
        today: 'Vandaag',
        month: 'Maand',
        week: 'Week',
        day: 'Dag',
        list: 'Lijst'
      },
      header: {
        left: '',
        center: '',
        right: ''
      },
      events: this.data,
      locale: 'nl',
      dayNamesShort: ["Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"],
    };
  }

  showMaandview() {
    this.today = moment(this.currentDate).locale('nl');
    let containerEl: JQuery = $('#calendar');
    var view = containerEl.fullCalendar('changeView', 'month', this.today);
    this.listviewShown = false;
    this.title = moment(this.today).locale('nl').format('MMMM YYYY');
  }

  showWeekview() {
    this.today = moment(this.currentDate).locale('nl');
    let containerEl: JQuery = $('#calendar');
    var view = containerEl.fullCalendar('changeView', 'agendaWeek', this.today);
    var weekNumber = moment(this.today).isoWeek();
    this.title = "Week " + weekNumber;
    this.listviewShown = false;
  }

  showDayview() {
    this.today = moment(this.currentDate).locale('nl').format('YYYY-MM-DD');
    let containerEl: JQuery = $('#calendar');
    containerEl.fullCalendar('changeView', 'agendaDay', this.today);
    this.title = moment(this.today).locale('nl').format('dddd') + " " + moment(this.today).locale('nl').format('DD-MM-YYYY');
    this.listviewShown = false;
  }

  showMonthViewToday() {
    this.today = moment(this.currentDate).locale('nl');
    let containerEl: JQuery = $('#calendar');
    var view = containerEl.fullCalendar('changeView', 'month', this.today);
    this.listviewShown = false;
    this.title = moment(this.today).locale('nl').format('MMMM YYYY');
  }

  prev() {
    let containerEl: JQuery = $('#calendar');
    var view = containerEl.fullCalendar('getView');
    switch (view.name) {
      case 'month': {
        containerEl.fullCalendar('prev');
        var previousMonth = moment(this.today).subtract(1, 'month').locale('nl');
        this.today = previousMonth;
        this.title = moment(previousMonth).locale('nl').format('MMMM YYYY');
        break;
      }

      case 'agendaWeek': {
        containerEl.fullCalendar('prev');
        var previousWeek = moment(this.today).subtract(1, 'week').locale('nl');
        var weekNumber = moment(previousWeek).isoWeek();
        this.today = previousWeek;
        this.title = "Week " + weekNumber;
        break;
      }

      case 'agendaDay': {
        containerEl.fullCalendar('prev');
        var previousDay = moment(this.today).subtract(1, 'days').locale('nl');
        this.today = previousDay;
        this.title = moment(previousDay).locale('nl').format('dddd') + " " + moment(this.today).locale('nl').format('DD-MM-YYYY');
        break;
      }
    }
  }

  next() {
    let containerEl: JQuery = $('#calendar');
    var view = containerEl.fullCalendar('getView');
    switch (view.name) {
      case 'month': {
        containerEl.fullCalendar('next');
        var nextMonth = moment(this.today).add(1, 'month').locale('nl');
        this.today = nextMonth;
        this.title = moment(nextMonth).locale('nl').format('MMMM YYYY');
        break;
      }

      case 'agendaWeek': {
        containerEl.fullCalendar('next');
        var nextWeek = moment(this.today).add(1, 'week').locale('nl');
        var weekNumber = moment(nextWeek).isoWeek();
        this.today = nextWeek;
        this.title = "Week " + weekNumber;
        break;
      }

      case 'agendaDay': {
        containerEl.fullCalendar('next');
        var nextDay = moment(this.today).add(1, 'days').locale('nl');
        this.today = nextDay;
        this.title = moment(nextDay).locale('nl').format('dddd') + " " + moment(this.today).locale('nl').format('DD-MM-YYYY');
        break;
      }
    }
  }

  showListview() {
    this.listviewShown = true;
  }
}

Am i missing something something really stupid?

Could you help me?

**Comment by Jamaks** [comment]
Hi, it is problem official fullcalendar may be, 

You can make own header, and subscribe output events
