### ISSUE TITLE
Disable clickevent redirect to event url

### ISSUE THREAD

**Issue by Dannisgaard** [Jamaks/ng-fullcalendar#102]
Hi Jamaks
Thanks for your good work.

I have a page with ng-fullcalendar to manage the calendar and another page that shows the same events as a public calendar that only shows calendar events, so no option to edit.
On the administration calendar, a clickevent has to open a modal with an editing form. On this calendar, I would like to disable redirect to event url on clickevent.

Is it possible?

**Comment by Jamaks** [comment]
Hi, you can use `(eventClick)` without url https://github.com/Jamaks/ng-fullcalendar/blob/master/src/demo/app/event.service.ts#L60

**Comment by Dannisgaard** [comment]
No I need url for the public calendar.
