### ISSUE TITLE
Events: Create normal events and background events

### ISSUE THREAD

**Issue by w-veltman** [Jamaks/ng-fullcalendar#104]
Hi,

I know you can create background events by setting rendering to "background", but I would like to set rendering to "background" per event. So that not all events are background events, but only the events i specifically set to rendering: "background".

Is this possible?

With kind regards,

Wouter Veltman

**Comment by w-veltman** [comment]
Found the solution

**Comment by Andy1408** [comment]
@w-veltman could you share your solution?

**Comment by w-veltman** [comment]
Was eventually a very simple work-around. I created a CreateEvent function for the events to display and within that function I called another function that created the background events  for the calendar to display.

**Comment by Andy1408** [comment]
@w-veltman thanks!
