### ISSUE TITLE
select callback doenst work

### ISSUE THREAD

**Issue by PavelJacobo** [Jamaks/ng-fullcalendar#105]
I'm trying to use select callback, but, no answers is printed. nothing happens. ¿what should I do? THANKS

[ocupacion-local-admin.component.ts.txt](https://github.com/Jamaks/ng-fullcalendar/files/2145678/ocupacion-local-admin.component.ts.txt)
[ocupacion-local-admin.component.html.txt](https://github.com/Jamaks/ng-fullcalendar/files/2145680/ocupacion-local-admin.component.html.txt)

**Comment by Jamaks** [comment]
Hi! use output event `(select)`
```
html:

<ng-fullcalendar (select)="onSelect($event)" ...

ts:

...

onSelect(model) {
 // model event
} 
...

```
