### ISSUE TITLE
'minTime' are incompatible.

### ISSUE THREAD

**Issue by nicogaldo** [Jamaks/ng-fullcalendar#106]
I get this error when compile the app.

> ERROR in src/app/pages/turnos/turnos.component.ts(271,9): error TS2322: Type '{ editable: true; eventLimit: false; locale: string; timeFormat: string; allDaySlot: false; butto...' is not assignable to type 'Options'.
  Types of property 'minTime' are incompatible.
    Type 'string' is not assignable to type 'Duration'.

My calendar options:
```
this.calendarOptions = {
  editable: true,
  eventLimit: false,
  locale: 'es-ES',
  timeFormat: 'H:mm',
  allDaySlot: false,
  buttonText: {
    today: 'Hoy',
    month: 'Mes',
    week: 'Semana',
    day: 'Día',
    list: 'Lista'
  },
  header: {
    left: 'prev,next today',
    center: 'title',
    right: 'month,agendaWeek,agendaDay,listMonth'
  },
  defaultView: 'listWeek',
  minTime: '09:00:00',
  maxTime: '21:00:00',
  selectable: true,
  events: this.events
};
```

**Comment by nicogaldo** [comment]
fixed importing moment js:

```
import * as moment from 'moment';

/* ... */

this.calendarOptions = {
          /* ... */
          minTime: moment.duration('09:00:00'),
          maxTime: moment.duration('21:00:00'),
          /* ... */
}

```

**Comment by satheeshBB43** [comment]
Awesome job gays, Looking exactly this solution.

**Comment by satheeshBB43** [comment]
Thank you so much

**Comment by rizkyhello** [comment]
i am very helped, hopefully given blessings , thank's
