### ISSUE TITLE
updateEvent

### ISSUE THREAD

**Issue by andrejm7** [Jamaks/ng-fullcalendar#107]
Good morning, why does not updateEvent work?

this.ucCalendar.fullCalendar ('updateEvent', el);

How would I use this function?

**Comment by Jamaks** [comment]
Hi! Please use two binding models [(eventsModel)]="events"

**Comment by andrejm7** [comment]
@Jamaks Can you make an example in stackblitz?

**Comment by Jamaks** [comment]
@andrejm7 see https://github.com/Jamaks/ng-fullcalendar-demo/blob/a0ea7f43c8c6c9e0ae858ab63b166afc5f017c27/src/app/app.component.html#L5

**Comment by andrejm7** [comment]
sorry ... but I do not know how to make an update with this.
