### ISSUE TITLE
Update event every month

### ISSUE THREAD

**Issue by kbchandiran** [Jamaks/ng-fullcalendar#11]
while using the `this.ucCalendar.fullCalendar('rerenderEvents');` funtion it's shows following error
`ERROR TypeError: Cannot read property 'fullCalendar' of undefined
    at SafeSubscriber._next (dashboard.component.ts:96)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next (Subscriber.js:185)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next (Subscriber.js:125)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at CatchSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next (Subscriber.js:125)
    at CatchSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (map.js:83)
    at MapSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at DeferSubscriber.webpackJsonp.../../../../rxjs/OuterSubscriber.js.OuterSubscriber.notifyNext (OuterSubscriber.js:19)
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4502
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:194
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1349
globalZoneAwareCallback @ zone.js:1358
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2526
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:300
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:235
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:258
(anonymous) @ zone.js:2550
proto.(anonymous function) @ zone.js:1222
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
subscribeToResult @ subscribeToResult.js:22
webpackJsonp.../../../../rxjs/observable/DeferObservable.js.DeferSubscriber._callFactory @ DeferObservable.js:94
webpackJsonp.../../../../rxjs/observable/DeferObservable.js.DeferSubscriber.tryDefer @ DeferObservable.js:85
DeferSubscriber @ DeferObservable.js:81
webpackJsonp.../../../../rxjs/observable/DeferObservable.js.DeferObservable._subscribe @ DeferObservable.js:71
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../../src/app/dashboard/dashboard.component.ts.DashboardComponent.getBookingList @ dashboard.component.ts:84
webpackJsonp.../../../../../src/app/dashboard/dashboard.component.ts.DashboardComponent.ngOnInit @ dashboard.component.ts:64
checkAndUpdateDirectiveInline @ core.es5.js:10834
checkAndUpdateNodeInline @ core.es5.js:12330
checkAndUpdateNode @ core.es5.js:12269
debugCheckAndUpdateNode @ core.es5.js:13130
debugCheckDirectivesFn @ core.es5.js:13071
(anonymous) @ DashboardComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13056
checkAndUpdateView @ core.es5.js:12236
callViewAction @ core.es5.js:12601
execEmbeddedViewsAction @ core.es5.js:12559
checkAndUpdateView @ core.es5.js:12237
callViewAction @ core.es5.js:12601
execComponentViewsAction @ core.es5.js:12533
checkAndUpdateView @ core.es5.js:12242
callWithDebugContext @ core.es5.js:13456
debugCheckAndUpdateView @ core.es5.js:12996
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10167
(anonymous) @ core.es5.js:4805
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4805
(anonymous) @ core.es5.js:4683
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4683
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:444
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:464
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:288
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:208
drainMicroTaskQueue @ zone.js:596
Promise resolved (async)
scheduleMicroTask @ zone.js:579
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:235
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:830
ZoneAwarePromise.then @ zone.js:919
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4536
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4521
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap 1a9309144e2beca9700e:54
3 @ main.bundle.js:6947
__webpack_require__ @ bootstrap 1a9309144e2beca9700e:54
webpackJsonpCallback @ bootstrap 1a9309144e2beca9700e:25
(anonymous) @ main.bundle.js:1`

**Comment by Jamaks** [comment]
Look please this project: https://stackblitz.com/edit/ng-fullcalendar-demo-fyfcfw?file=app%2Fapp.component.ts method updateEvents() and oldEvents() . Show me your project, please.

**Comment by kbchandiran** [comment]
Thank you so much, it's working fine. Thanks for the project reference
