### ISSUE TITLE
Update the peer dependencies for allowing angular 6 versions

### ISSUE THREAD

**Issue by jonathanspence** [Jamaks/ng-fullcalendar#110]
currently getting two npm warnings:

npm WARN ng-fullcalendar@1.6.1 requires a peer of @angular/core@>=4.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN ng-fullcalendar@1.6.1 requires a peer of @angular/common@>=4.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.

Can you update the peer dependencies to support Angular 6? I would really appreciate it!

Similar to ralberts pull request for Angular 5 in February: https://github.com/Jamaks/ng-fullcalendar/pull/42

**Comment by Jamaks** [comment]
done!  use ng-fullcalendar 1.6.2
