### ISSUE TITLE
Events are not updating after http call 

### ISSUE THREAD

**Issue by Mean563** [Jamaks/ng-fullcalendar#12]

**Comment by Jamaks** [comment]
Events update after subscribe http, look this project 
 https://stackblitz.com/edit/ng-fullcalendar-demo-fyfcfw?file=app%2Fapp.component.ts methods updateEvents() and oldEvents()

**Comment by Mean563** [comment]
Hi @Jamaks , Thanks your comments and answer but i was trying same thing. but  For Http call response I am getting different data structure But I am Converting to compatible structure, after I made the data change I am calling 

  ```
 this.calendarOptions = {
        editable: true,
        eventLimit: false,
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,agendaWeek,agendaDay,listMonth'
        },
        events: data,
        
      }; 
```

But not updating can you help me something, I was tried 

```
 data.forEach(el => {
        this.ucCalendar.fullCalendar('renderEvent', el);
      });
```

But it is saying `fullCalendar` is undefined.

**Comment by Mean563** [comment]
@Jamaks , Why first time events is not populating in calendar. any help from you. Thanks in advance !!

**Comment by Jamaks** [comment]
You forgot to insert the render function
'''
 data.forEach(el => {
        this.ucCalendar.fullCalendar('renderEvent', el);
      });
this.ucCalendar.fullCalendar('rerenderEvents', el);
'''

**Comment by Jamaks** [comment]
this.ucCalendar.fullCalendar('rerenderEvents');

**Comment by Mean563** [comment]
Hi @Jamaks , Thank you so much your helping but still  I am getting error, I am trying below code , but I am getting error 👍 
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { CalendarComponent } from 'ng-fullcalendar';
import { Options } from 'fullcalendar';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  calendarOptions: Options;
  @ViewChild(CalendarComponent) ucCalendar: CalendarComponent;

  constructor() { }


  ngOnInit() {
    let data = [
      {
        "id": 1,
        "name": "cerulean",
        "year": 2000,
        "color": "#98B2D1",
        "pantone_value": "15-4020",
        "date": "2017-12-09"
      },
      {
        "id": 2,
        "name": "fuchsia rose",
        "year": 2001,
        "color": "#C74375",
        "pantone_value": "17-2031",
        "date": "2017-12-13"
      },
      {
        "id": 3,
        "name": "true red",
        "year": 2002,
        "color": "#BF1932",
        "pantone_value": "19-1664",
        "date": "2017-12-22"
      }
    ];
    this.calendarOptions = {
      editable: true,
      eventLimit: false,
      height: 600,
      header: {
        left: 'prev',
        center: 'title',
        right: 'next'
      },


    };

    data.forEach(function (item) {
      let object = {
        title: '',
        start: ''
      }

      object.title = item.name;
      object.start = item.date;
      
      this.ucCalendar.fullCalendar('renderEvent', object);
   
    });

     this.ucCalendar.fullCalendar('rerenderEvents')
```

I am getting below error : `ERROR TypeError: Cannot read property 'ucCalendar' of undefined`

**Comment by Jamaks** [comment]
Use
```js
-> data.forEach(item => {
     this.ucCalendar.fullCalendar('renderEvent', object);
 });

data.forEach(function (item) {
});
```
and learn javascript please https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by Mean563** [comment]
Hi @Jamaks , Thanks for helping and Thanks for your valuable suggestion. Thanks A lot.

**Comment by Mean563** [comment]
@Jamaks  It is working fine. but what i was asking and what you shared both are different but Thanks for your cool Help. great  help :+1:

**Comment by Jamaks** [comment]
@Mean563 create your project in stackblitz please and show me
