### ISSUE TITLE
Swipe calender for next/prev

### ISSUE THREAD

**Issue by Shtibel** [Jamaks/ng-fullcalendar#120]
Hi there,
I am implementing ng-fullcalendar on my Ionic app.
I want to add option to navigate next/prev by swiping right/left.

How can I add this functionality ?

Thank you.

**Comment by Jamaks** [comment]
Hi! use https://github.com/HsuanXyz/ion2-calendar for ionic,
or use hammerjs 
(swipeleft)
(swiperight)
