### ISSUE TITLE
Impossible to customize event view

### ISSUE THREAD

**Issue by sergiogren** [Jamaks/ng-fullcalendar#121]
Hello,
I have noticed that using eventRender callback in this.calendarOptions object doesn't affect to event view. Also I've noticed that this callback doesn't fire at all. If this is a known bug, could you tell me how to fix it? If not, could you tell me how to customize event view?
Thank you.

**Comment by Jamaks** [comment]
Hi! you may use `viewRender` event or binding `(event)`

**Comment by hristoivanov1994** [comment]
Hello, Jamaks. I think I have similar issue, I want to customize the html of an event, for example add <hr> under the event title, I tried with viewRender, still not sure how to implement it. I use the example that you gave in https://stackblitz.com/edit/ng-fullcalendar-demo , if you can show how it should be implement I will appreciate it... still new with angular

**Comment by hristoivanov1994** [comment]
> Hi! you may use `viewRender` event or binding `(event)`

Hello, Jamaks. I think I have similar issue, I want to customize the html of an event, for example add
under the event title, I tried with viewRender, still not sure how to implement it. I use the example that you gave in https://stackblitz.com/edit/ng-fullcalendar-demo , if you can show how it should be implement I will appreciate it... still new with angular

**Comment by Jamaks** [comment]
@hristoivanov1994 try use (clickButton)="clickButton($event.detail)

**Comment by hristoivanov1994** [comment]
Well, I don't want to change anything on click event, but while the events are rendered, so i tried at first with eventRender.
in .html
(eventRender)="eventRender($event.detail)" or like (event)="eventRender($event.detail)"
...
in .ts
  eventRender($model: any){
    $model = {
      event: {
        title: $model.event.title+"<hr>",,
      },
      duration: {}
    }
   return $model;
  }
The effect that i want to achieve is to add underline under the title of every event at the time they are rendered.
![from](https://user-images.githubusercontent.com/17101084/45417618-463e5680-b68b-11e8-9683-f2a4f7f93130.PNG)

to

![to](https://user-images.githubusercontent.com/17101084/45417642-4e969180-b68b-11e8-9f73-6cfc63035209.PNG)

**Comment by hristoivanov1994** [comment]
> @hristoivanov1994 try use (clickButton)="clickButton($event.detail)

Well, I don't want to change anything on click event, but while the events are rendered, so i tried at first with eventRender.
in .html
(eventRender)="eventRender($event.detail)" or like (event)="eventRender($event.detail)"
...
in .ts
eventRender($model: any){
$model = {
event: {
title: $model.event.title+"underline"
},
duration: {}
}
return $model;
}
The effect that i want to achieve is to add underline under the title of every event at the time they are rendered.

like: 
![from](https://user-images.githubusercontent.com/17101084/45417733-89002e80-b68b-11e8-96be-eafa799618d8.PNG)
to
![to](https://user-images.githubusercontent.com/17101084/45417743-8ef60f80-b68b-11e8-9779-909ed49b0e35.PNG)

**Comment by Jamaks** [comment]
@hristoivanov1994 @sergiogren 
 Special for you https://stackblitz.com/edit/ng-fullcalendar-demo-jcygvd?file=app%2Fapp.component.ts

**Comment by hristoivanov1994** [comment]
Ooh... yes I see it now!Thank you so much and sorry for disturbing you with stupid things

**Comment by Jamaks** [comment]
> Ooh... yes I see it now!Thank you so much and sorry for disturbing you with stupid things

Click Star button please;)
