### ISSUE TITLE
Getting $(...).fullCalendar is not a function

### ISSUE THREAD

**Issue by Shtibel** [Jamaks/ng-fullcalendar#122]
Hi there

I am trying to user jQuery to refech events.
I need jQuery becuse I have multiple calendars and I cant find other way to handel them.
So I give each one a diferent ID and when I wnat to reload one I send its ID.
But I get error: 

    $(...).fullCalendar is not a function

What can be the problem?

I have this code HTML:

    <ng-fullcalendar [id]="'ucCalendar'+i" 
        #ucCalendar0
        [options]="slide.calendarOptions" 
        (viewRender)="renderViewColumns($event.detail)"
        (eventClick)="fullCalendarEventClick($event.detail)"
        (eventAfterRender)="fullCalendarInitialized($event.detail)"
    ></ng-fullcalendar>

And .ts code:

    refreshMe(id){
        $('#ucCalendar'+id).fullCalendar('refetchEvents');
    }

**Comment by Jamaks** [comment]
Hi! use
 
```ts
@ViewChild(CalendarComponent) ucCalendar0: CalendarComponent;

refreshMe(){
    this.ucCalendar0.fullCalendar('refetchEvents');
}
```
