### ISSUE TITLE
Show message on the calendar after adding an event for a day

### ISSUE THREAD

**Issue by liamngth** [Jamaks/ng-fullcalendar#128]
Hello,
I am facing an issue with the way to show an message on the calendar after adding an event to it
Steps I have tried are:
1. Select a or multiple days then a dialog will open and I can  input some fields for those days
2. Then I will get those events and add them as  events: [title: ' An event is coming', start: a date]

So what I am expecting is, after a book of the event for those days successfully, the calendar should show an message on it. But nothing show here, I have to refresh my page to load those messages

Is there a way to solve this issue? Please guide me

**Comment by Jamaks** [comment]
Hi! you can try use `[eventsModel]` 

or show your issue stackblitz example

**Comment by liamngth** [comment]
Hi Jamaks,
Thanks, I tried using [eventsModel] and solved my case.
