### ISSUE TITLE
eventRender function in options

### ISSUE THREAD

**Issue by MadEddieFFS** [Jamaks/ng-fullcalendar#14]
I was trying to use the function eventRender which is passed through in the CalendarOptions as below:

eventRender: function (event, element) {
                console.log('Rendering event', event);
                return true;
            },

From the fullcalendar documentation: https://fullcalendar.io/docs/event_rendering/eventRender/

Is this possible or am I implementing it incorrectly ?

The issue is that the function does not appear to run.

**Comment by Jamaks** [comment]
Output 8 EventEmitter (eventRender)="eventRenderFunction($event.detail)", version 1.2.0

**Comment by Jamaks** [comment]
Update to version 1.2.0
