### ISSUE TITLE
How can i change the theme system?

### ISSUE THREAD

**Issue by marianorv** [Jamaks/ng-fullcalendar#142]
How can i change the theme system on the calendar?

**Comment by marianorv** [comment]
thanks! its works 👍

**Comment by stolotti** [comment]
Suggesting to use another component does not solve the problem.
How can we change default theme?
I'vre tried to add themeSystem="" directive but it seems not working

**Comment by irustm** [comment]
@stolotti you about https://fullcalendar.io/docs/themeSystem ?

**Comment by stolotti** [comment]
In demo page I can see a lot of themes... How can I apply them?

**Comment by irustm** [comment]
Maybe we forgot about this parameter in angular. I'll look at it later.

**Comment by irustm** [comment]
You should be add plugins:

` [ bootstrapPlugin ],`
and use config 
`[themeSystem]="'bootstrap'"`

see doc please https://fullcalendar.io/docs/bootstrap-theme
