### ISSUE TITLE
Module ''fullcalendar'' has no exported member 'Options'.

### ISSUE THREAD

**Issue by dwilanang** [Jamaks/ng-fullcalendar#15]
I try to use this modul in my project Now
However, when I run my project there was an error in the modul
The error is as follow
ERROR in ../node_modules/ng-fullcalendar/src/calendar.component.d.ts (3,10): Module ''fullcalendar'' has no exported member 'Options'.
Kindly assist me to fix the problem

**Comment by Jamaks** [comment]
try install 
``` npm i --save fullcalendar ```

**Comment by AltRoot17** [comment]
Same issue :(

**Comment by dscuderiex** [comment]
Same for me.
I tried install fullcalendar but not working

**Comment by AltRoot17** [comment]
I  tried more than 7  hours fix for this issue, but cant do that, any solution?

**Comment by dscuderiex** [comment]
The last version have problems, i go back to version 1.0.3 and is working fine

**Comment by Jamaks** [comment]
@dwilanang @AltRoot17 @dscuderiex  update please to version 1.2.1

**Comment by dwilanang** [comment]
@AltRoot17 not yet i'm still trying :)

**Comment by fabrizziocht** [comment]
Good night, I have updated to 1.2.1 but I got the same problem

**Comment by dwilanang** [comment]
yeaaay..
it's working fine
thanks a lot

**Comment by AltRoot17** [comment]
Woe brilliant, Now its work for me

**Comment by Jamaks** [comment]
@fabrizziocht clear node_modules and ```npm install```

**Comment by anantksingh** [comment]
Module '"fullcalendar"' has no exported member 'Options'.

**Comment by anantksingh** [comment]
Module '"fullcalendar"' has no exported member 'Options'.
