### ISSUE TITLE
Make an event when calendar is fully initialized

### ISSUE THREAD

**Issue by sherlock1982** [Jamaks/ng-fullcalendar#19]
For some reason you call setTimeout for 100 millisesonds in ngAfterViewInit. But parent component needs to know when calendar will be ready to accept events.

For example in parent ngAfterViewInit I start calling calendar functions and they fail because calendar is still not even created.

**Comment by Jamaks** [comment]
Special for you, update please version 1.3.0
```(initialized)="initialized()" ```
