### ISSUE TITLE
Module ''fullcalendar'' has no exported member 'Options'

### ISSUE THREAD

**Issue by igasparetto** [Jamaks/ng-fullcalendar#23]
Hi there,

I am getting this error in my machine, but my colleagues are not (ok, you say MY machine is the problem):

/ng-fullcalendar/src/calendar.component.d.ts (3,10): Module ''fullcalendar'' has no exported member 'Options'.

But what can the problem be? We have the same configurations. The only difference is that I am on MacOS and the others are on Windows.

Thanks

**Comment by Jamaks** [comment]
Clean node_modules and update to version 1.3.0 . View #15 #17 . npm install fullcalendar@**3.6.1**
