### ISSUE TITLE
Tabs to dropdown menu

### ISSUE THREAD

**Issue by jimmylogic** [Jamaks/ng-fullcalendar#26]
Hi, I am trying to use dropdown instead of tabs to select month-week-day. But i think there is not any option to customize view.

**Comment by Jamaks** [comment]
try use https://fullcalendar.io/docs/display/customButtons/ or 
https://fullcalendar.io/docs/views/changeView/  

`this.ucCalendar.fullCalendar('changeView', 'agendaDay');`
`this.ucCalendar.fullCalendar('changeView', 'agendaWeek');`
...
