### ISSUE TITLE
Add support for select event

### ISSUE THREAD

**Issue by x3r10n** [Jamaks/ng-fullcalendar#27]
In the week agenda, you can click and drag to select a section. We should have an event emitter for that.
see : [https://fullcalendar.io/docs/selection/select_callback/](https://fullcalendar.io/docs/selection/select_callback/)

**Comment by x3r10n** [comment]
Fastest fix in the history of Github !! Thanks !

**Comment by xyrintech** [comment]
This does not seems to be working.

**Comment by Jamaks** [comment]
@xyrintech https://fullcalendar.io/docs/selection/selectable/
 ```{ ... selectable: true, ... }```
