### ISSUE TITLE
custom element in eventRender function

### ISSUE THREAD

**Issue by rocabertecp** [Jamaks/ng-fullcalendar#29]
Hello! I wanted to make a custom display for the events. 
Currently, I use the callback eventRender function in calendarOptions like this:

`eventRender: function(event, element) { `

      `element.html(
           "<div class='fc-content' data-event-id=" + event.id + ">" + 
               "<div class='fc-title col-xs-3'>" + event.title + "</div>" +
           "</div>"
       );`
`}`

The callback function eventRender seems to work on 1.1.0 version but it does not seem to work on later versions.
Any ideas on this?

**Comment by Jamaks** [comment]
Hi, try `rm -rf node_modules` and 
 `npm install --save fullcalendar@3.6.1`

**Comment by Jamaks** [comment]
`element` is not Jquery object
