### ISSUE TITLE
Add dayClick event

### ISSUE THREAD

**Issue by flomuson** [Jamaks/ng-fullcalendar#32]
Hello,

Could you add dayClick event ?
Thanks

**Comment by Jamaks** [comment]
Hi, ok. This feature will be in version 1.5.0 
and 5 new callbacks
```ts
navLinkDayClick (callback)
navLinkWeekClick (callback)
dayClick (callback)
eventMouseover (callback)
eventMouseout (callback)
```

**Comment by RODOBTA** [comment]
How can I use the day event Click to download the most current version where it works
