### ISSUE TITLE
fullCalendar is not a function

### ISSUE THREAD

**Issue by Kamilius** [Jamaks/ng-fullcalendar#33]
Getting following runtime error while trying to use `ng-fullcalendar` as in repo description:
`ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery___default(...)(...).fullCalendar is not a function`.
I'm using:
- Angular-cli v1.4.4
- Angular v4.4.4

Trying to use CalendarComponent from LazyLoaded module.

Any clues on what can be wrong here? For me it seems, that `fullCalendar` wasn't properly initialized for jQuery, or something similar.

Maybe I'm missing any additional packages?

**Comment by buu700** [comment]
I ran into the same issue, most likely because node_modules/jquery is 3.3.0 and node_modules/ng-fullcalendar/node_modules has a separate jquery that's 3.2.1.

**Comment by Kamilius** [comment]
@buu700 it bight be, but I don't have any jQuery explicitly added as dependency

**Comment by buu700** [comment]
Hm, well maybe fullcalendar something else is pulling in a second jQuery instance? This only started happening for me after 3.3.0 was released (and I'm not entirely sure why; seems like a bug in Yarn's flat dependency resolution), so it could be a similar root cause if it started for you at the same time.

**Comment by Jamaks** [comment]
@Kamilius  Show me please your package.lock file, and install `fullcalendar@3.6.1`

**Comment by Jamaks** [comment]
I maked local fixes, please remove path node_modules and install version 1.4.4 .

I did not find the exact reason. But I think that this issue is due to an angular/cli . With angular/cli 1.4.1 it's worked.  @Kamilius you use @angular/cli "1.6.5"

**Comment by Kamilius** [comment]
@Jamaks `1.4.6` version of which package? Angular CLI?

**Comment by Jamaks** [comment]
ng-fullcalendar@1.4.6

**Comment by Kamilius** [comment]
@Jamaks yeah `ng-fullcalendar@1.4.6` and `fullcalendar@3.6.1` fixes issue.
