### ISSUE TITLE
fullCalendar is not a function

### ISSUE THREAD

**Issue by amourinho** [Jamaks/ng-fullcalendar#35]
version installed "ng-fullcalendar": "1.4.0"

I get the error with a new project that imports your full calendar, and any old projects in which I redeploy.

ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery___default(...)(...).fullCalendar is not a function
at ng-fullcalendar.es5.js:55

TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery___default(...)(...).fullCalendar is not a function
at CalendarComponent.webpackJsonp.../../../../ng-fullcalendar/ng-fullcalendar.es5.js.CalendarComponent.fullCalendar (ng-fullcalendar.es5.js:195)

**Comment by Jamaks** [comment]
I maked local fixes, please remove path node_modules and install version 1.4.4 .
