### ISSUE TITLE
Update Event

### ISSUE THREAD

**Issue by c4mel** [Jamaks/ng-fullcalendar#37]
How to update event attributes (color, title...) and render in the calendar?

**Comment by Jamaks** [comment]
You can delete and recreate events
```
 this.ucCalendar.fullCalendar( 'removeEvents', [5] );
 this.ucCalendar.fullCalendar('renderEvent', el);
 this.ucCalendar.fullCalendar('rerenderEvents');
```
or #34 [ngSource] in future version ng-fullcalendar 1.5.0

**Comment by TyreX6** [comment]
item in your example  is an array, are you sure that will work !!

**Comment by llojkue** [comment]
Hi, you can use eventsModel attribute to pass events to calendar.

``` html
<ng-fullcalendar
    [options]="calendarOptions"
    [eventsModel]="calendarEvents"
    (clickButton)="onClickButton($event)"></ng-fullcalendar>
```
