### ISSUE TITLE
FC is not defined line ng-fullcalendar.es5.js:50 

### ISSUE THREAD

**Issue by dscuderiex** [Jamaks/ng-fullcalendar#39]
Today when i updated ng-fullcalendar this error occurred.
How can i fixed?
Thanks

**Comment by dscuderiex** [comment]
Hi. Is solved
The problem was a call for inexistent function.
Thanks for u help.
Regards

**Comment by anam-khalid** [comment]
@dscuderiex  @Jamaks  Can you please share the solution for this?

**Comment by SBCDevelopers** [comment]
Solution please, I'm facing the same problem.
