### ISSUE TITLE
Package version mismatch on npm and github 

### ISSUE THREAD

**Issue by jimmylogic** [Jamaks/ng-fullcalendar#40]
I have an issue with source code 
when I download it from npm it shows different code and when i clone from github it shows different code
![screenshot from 2018-02-02 15-07-32](https://user-images.githubusercontent.com/13450220/35726433-e54e760c-082a-11e8-942b-f2d8446483a7.png)
![screenshot from 2018-02-02 15-08-05](https://user-images.githubusercontent.com/13450220/35726435-e5920c14-082a-11e8-880e-66021895472d.png)

**Comment by Jamaks** [comment]
npm contains the code after build (`dist` path)
 example https://github.com/Jamaks/ng-fullcalendar/tree/1.4.4-local-fix-fullCalendar-not-found/dist
