### ISSUE TITLE
Body not rendering without resizing window

### ISSUE THREAD

**Issue by OzoTek** [Jamaks/ng-fullcalendar#41]
Hi,

I am trying to use your library but I can't get the body to be displayed. As shown by the screenshot, I only have the header.

<img width="1165" alt="screen shot 2018-02-02 at 10 09 55" src="https://user-images.githubusercontent.com/6436053/35739938-4875da92-0801-11e8-8986-d1cd6f74bbd6.png">

I reduced the https://stackblitz.com/edit/ng-fullcalendar-demo at the very minimum code and it's working there, so I assume I am missing something on my side, but can't figure out what.

Setup:

fullcalendar: 3.6.1
ng-fullcalendar: ^1.4.6
jquery: 3.3.1

It's worth noting that I have my fullcalendar working with an angularJS wrapper, I'm just migrating to Angular 4+.

Thanks.

EDIT: Oh well actually it's just a rendering issue, it gets displayed if I resize the window or click on the next/prev button, not sure why this happens though

**Comment by Jamaks** [comment]
Hi, see please demo project https://github.com/Jamaks/ng-fullcalendar-demo , 
Show me package-lock.json file.  Are there any errors in the console?

**Comment by OzoTek** [comment]
Hi,

No I don't get any errors, nor do I have something drastically different from the demo project you sent me.
I noticed that if I come from a different URL of my web app it gets displayed correctly, but not if I type the URL or refresh the page while on the calendar.

I don't have a package-lock.json.
