### ISSUE TITLE
Can we use this FullCalendar Module in angular5 project?

### ISSUE THREAD

**Issue by kapilkk** [Jamaks/ng-fullcalendar#43]

**Comment by Jamaks** [comment]
You can use it in future version 1.5.0

**Comment by lunatixcoder** [comment]
I am using it with Angular5... however, I followed all the instructions and it throws an error during ng serve but sometimes it continues to compile and it runs correctly.

webpack: Compiling...
 69% building modules 2067/2083 modules 16 active ...dules/rxjs/observable/bindCallback.jsERROR in node_modules/fullcalendar/dist/fullcalendar.d.ts(695,36): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(696,29): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(697,20): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(759,22): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(775,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(988,23): error TS2304: Cannot find name 'JQueryEventObject'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1401,70): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1603,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(1623,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/fullcalendar/dist/fullcalendar.d.ts(2588,50): error TS2304: Cannot find name 'JQueryPromise'.
node_modules/ng-fullcalendar/src/calendar.component.d.ts(3,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.
src/app/dashboard/dashboard.component.ts(10,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.

Date: 2018-02-12T21:58:01.545Z - Hash: fb185c8db364026d02ee - Time: 24303ms               
3 unchanged chunks
chunk {admin.module} admin.module.chunk.js () 346 kB  [rendered]
chunk {dashboard.module} dashboard.module.chunk.js () 386 kB  [rendered]
chunk {error.module} error.module.chunk.js () 25.6 kB  [rendered]
chunk {landing.module} landing.module.chunk.js () 117 kB  [rendered]
chunk {main} main.bundle.js (main) 1.86 MB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 609 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 36.4 MB [initial] [rendered]

webpack: Compiled successfully.


Other times, it just fails during compile.  Its weird that if I compile it and it fails but then I just resave one file in my component it autorecompiles, throws the same error but then continues to finish and works.

**Comment by sebastian-zarzycki-es** [comment]
Any idea when 1.5.0 will be released?

**Comment by Jamaks** [comment]
@sebastian-zarzycki-es  28.02.2018

**Comment by kapilkk** [comment]
Hi,
While I'm using vertical resource view, as the number of "Rooms" increases they shrink in size, so is there any way so that we can provide horizontal scrolling in calendars itself so that the size of "Rooms" remain constant.
