### ISSUE TITLE
When loading events with callback error occurs (TypeError: events.forEach is not a function)

### ISSUE THREAD

**Issue by zlatoroh** [Jamaks/ng-fullcalendar#53]
Hi,

I'm loading events with callback function

```
events: function(start, end, timezone, callback) {
                        Observable.forkJoin(
                            that.selectedSubconstractors.map(subcon => {
                                return that.commonRest.getReservationList(that.loggedUser.contractorId, subcon.id, start.format('YYYY-MM-DD'), end.format('YYYY-MM-DD'))
                                .map(res => res.json());
                            })
                        ) .subscribe(res => {
                            let allEvents = Array.prototype.concat(...res).map(event => {
                                return new Event().deserialize(event);
                            });
                            callback(allEvents);
                        })
```
The first time is ok, but when I change view an error occurs:

> zone.js:192 Uncaught TypeError: events.forEach is not a function
>     at CalendarComponent.renderEvents (ng-fullcalendar.es5.js:336)
>     at eval (ng-fullcalendar.es5.js:141)
>     at Array.forEach (<anonymous>)
>     at HTMLButtonElement.eval (ng-fullcalendar.es5.js:137)
>     at HTMLButtonElement.dispatch (jquery.js:5206)
>     at HTMLButtonElement.elemData.handle (jquery.js:5014)
>     at ZoneDelegate.invokeTask (zone.js:421)
>     at Zone.runTask (zone.js:188)
>     at ZoneTask.invokeTask [as invoke] (zone.js:496)
>     at invokeTask (zone.js:1517)

It looks like the function` events.forEach(function (el) {` expest an array of data and not a callback fuction.

Thank you!

**Comment by Jamaks** [comment]
Hi, events in `ng-fullcalendar^@1.5.0` only array
