### ISSUE TITLE
this.ucCalendar.fullCalendar('changeView', 'agendaDay', date) always changes to same day, ???

### ISSUE THREAD

**Issue by eltonec** [Jamaks/ng-fullcalendar#56]

**Comment by Jamaks** [comment]
Look please https://fullcalendar.io/docs/changeView or  share your project in stackbltz

**Comment by eltonec** [comment]
Sorry i dont know how to put my project in stackbltz, but we can use the demo project, just add 'navLinks: true' to this.calendarOptions and then click day number on month view you will observe the problem( always change date to first click day).

**Comment by Jamaks** [comment]
It is bug fullcalendar example http://jsfiddle.net/4g8gfy11/1/
and resolve
https://stackoverflow.com/questions/7072194/fullcalendar-jump-to-agendaday-from-month-view-when-date-is-picked

**Comment by eltonec** [comment]
Thanks a lot!!!
