### ISSUE TITLE
eventsModel binding is not working properly on array push

### ISSUE THREAD

**Issue by dorthrithil** [Jamaks/ng-fullcalendar#59]
If I push a new event to `this.events` the calendar view is not updated. 

However the view is updated if replace the whole collection of events with different events.

**Comment by Jamaks** [comment]
becouse only set [eventsModel] https://github.com/Jamaks/ng-fullcalendar/blob/master/src/lib/src/calendar.component.ts#L21

**Comment by Jamaks** [comment]
@dorthrithil , It will be in the next release

**Comment by TyreX6** [comment]
When it will be published the next release please ?

**Comment by blahblahyaya** [comment]
> because only set [eventsModel] https://github.com/Jamaks/ng-fullcalendar/blob/master/src/lib/src/calendar.component.ts#L21

What do you mean by "because only set [eventsModel]? How do I implement that?

**Comment by Jamaks** [comment]
> > because only set [eventsModel] https://github.com/Jamaks/ng-fullcalendar/blob/master/src/lib/src/calendar.component.ts#L21
> 
> What do you mean by "because only set [eventsModel]?" How do I implement that?

in html
```html
<ng-fullcalendar [(eventSource)]="events"> <ng-fullcalendar>

```

In ts
```ts

clear() {
    this.events = [];
}
update() {
    this.events = [
      {
        // new events
      }
   ];
}
```
