### ISSUE TITLE
calendar becomes super slow with a few hundreds events

### ISSUE THREAD

**Issue by colorcube** [Jamaks/ng-fullcalendar#63]
The initial rendering and every click takes around 10 seconds with a few hundreds events.

I think there are two things that causes the problem.

renderEvents() add each event individually. As I understand rendering is triggered for every event.

I changed the method to:

```
  renderEvents(events: EventSourceInput) {
    $(this.element.nativeElement).fullCalendar('removeEvents');
    $(this.element.nativeElement).fullCalendar('addEventSource', events);
  }
```

The second thing is rerendering on button click. I don't see why the commented lines are needed in the click handler:

```
                //this.renderEvents(this._eventsModel);
                eventDispatch(name);
                //$(this.element.nativeElement).fullCalendar('rerenderEvents');
```

I'm not sure if the above is a fix or maybe break something. For me the calendar is fast again.

**Comment by Jamaks** [comment]
Hi! make please pull request, with changes

**Comment by Jamaks** [comment]
Because this is a fullcalendar bug. When you add a new event to the calendar and switch between months, these events disappear. So I have to store the state and redraw every time I change

Example:
http://jsfiddle.net/1hq87daq/
