### ISSUE TITLE
this.ucCalendar not found

### ISSUE THREAD

**Issue by mikenlanggio** [Jamaks/ng-fullcalendar#67]
I tried use this.ucCalendar (like demo code), but it is undefined.
I went wrong?

**Comment by Jamaks** [comment]
View please https://github.com/Jamaks/ng-fullcalendar-demo

**Comment by mikenlanggio** [comment]
Thank you,
But is not working :(

**Comment by Jamaks** [comment]
Show me please screen or console errors

**Comment by mikenlanggio** [comment]
This is my code:
https://uphinhnhanh.com/images/2018/03/26/image15563.png
This is console error:
https://uphinhnhanh.com/images/2018/03/26/imagec0fb3.png
Thank you

**Comment by Jamaks** [comment]
Use this.usCalendar after initialized fullcalendar 
component.html
```
<ng-fullcalendar (initialized)="initialized()"  ... ></ng-fullcalendar>
```

component.ts
```
initialized() {
      console.log('Initialized compleate');
      // your code
}
```

example https://github.com/Jamaks/ng-fullcalendar/blob/af3869cfbb13929112722fc25dfc7ab45e73c7bc/src/demo/app/home/home.component.ts#L94

**Comment by mikenlanggio** [comment]
Thank you so much!! :)

**Comment by jbbergy** [comment]
initialized input save my life :) thanks
