### ISSUE TITLE
How to add new event?

### ISSUE THREAD

**Issue by salih0313** [Jamaks/ng-fullcalendar#70]
I need to add new event ({id:1, start:"...", end:"..."})  with existing list. 

I have tried this

 customButtons: {
        addEventButton: {
          text: 'Add Event',
          click: function() {
           console.log('btn clicked...')
          //  how can i open modal here
          }
        }
      }

**Comment by Jamaks** [comment]
customButtons property not supported in 1.5v. I will implement it in the next release.

**Comment by Jamaks** [comment]
Dublicate #65
