### ISSUE TITLE
How to bind multiple ng-fullcalendar options in  one page ?

### ISSUE THREAD

**Issue by xathu** [Jamaks/ng-fullcalendar#76]
Even in bind two options in ts and html but its only work with first options. 
ShowcalendarOptions: Options;
calendarOptions:Options;
                <ng-fullcalendar  [options]="ShowcalendarOptions" ></ng-fullcalendar>
                <ng-fullcalendar #ucCalendar [options]="calendarOptions" ></ng-fullcalendar>

**Comment by sheikalthaf** [comment]
@xathu @Jamaks @mariohmol It is must wanted feature for this library. Any timline to fix this?

**Comment by Jamaks** [comment]
sorry, I do not have much time, send me please pull reqests

**Comment by denzel-tlt** [comment]
@Jamaks, I created the new pull request. Hope that it can fix the issue.

**Comment by Jamaks** [comment]
@denzel-tlt  I supplemented the code, what you offered is not enough.
and merge your code 
@xathu @sheikalthaf please install ng-fullcalendar 1.5.6
