### ISSUE TITLE
please remove the repo

### ISSUE THREAD

**Issue by amineparis** [Jamaks/ng-fullcalendar#79]
this one is so far better I have wasted one week with this after discovering that https://github.com/mattlewis92/angular-calendar

Remove it so that people don't waste more time like I did

It's also bad to disperse open source contribution workforce upon many plugins that serve the same need

**Comment by Jamaks** [comment]
This repository wrapper over fullcalendar and does not claim to be the best implementation

**Comment by amineparis** [comment]
and it's not please remove it so that people use the best, please think of others before thinking of your name visibility, I have wasted weeks trying to adapt with it, it's not at all customisable; not at all angular friendly, huge performance loose, etc.

**Comment by Jamaks** [comment]
you should have assessed the risks in advance. this library is needed to quickly perform tasks.

**Comment by ralberts** [comment]
This repo is very different from the link @amineparis gave.  I decided to use this repo as I wanted the fullcalendar wrapper rather then the other library and the way it's calendar works.

**Comment by raphael22** [comment]
"Your free open-source lib doesn't fit my project so it suck"
What ?
