### ISSUE TITLE
Emit event?

### ISSUE THREAD

**Issue by stehag** [Jamaks/ng-fullcalendar#8]
this.options.eventClick = function (event) {
            let detail: UpdateEventModel = { event: event, duration: null };
            var widgetEvent = new CustomEvent('eventClick', {
                bubbles: true,
                detail: detail
            });
            elem[0].dispatchEvent(widgetEvent);
        };

Couldn't this simply be rewritten to use the eventemitter?
Like:  
this.options.eventClick = (event) => {
            this.eventClick.emit(event);
};
Or am i missing something here?

**Comment by Jamaks** [comment]
No, because fullcalendar takes exactly the function, before rendering and wraps it. you can not throw a reference to the eventemitter. Therefore, dispatchevent is called native
