### ISSUE TITLE
'string' is not assignable to type 'Duration'

### ISSUE THREAD

**Issue by churro90** [Jamaks/ng-fullcalendar#88]
I'm defining the calendar options as follows:
```
  this.calendarOptions = {
      editable: true,
      eventLimit: false,
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listMonth'
      },
      buttonText: {
        today: 'Hoy',
        month:    'Mes',
        week:     'Semana',
        day:      'Día',
        list:     'Lista'
      },
      aspectRatio: 2,
      minTime: '08:00:00',
      maxTime: '22:00:00',
      slotDuration: '00:00:15',
      slotLabelInterval: '00:01:00',
      locale: 'es-CL',
      events: this.eventos
    };
```
However I keep getting this error although the calendar is rendering correctly. Any idea how to bypass this? The problem is with defining durations as a string I guess but it is supposed to be the correct format

**Comment by Dekminoz** [comment]
Hi, 

I have bypass the problem  , by passing all duration like minTIme,maxTime etc with moment.duration like this : moment.duration('08:00:00') .

 If you need with parameters you can check, parameter type in index.d.ts . exemple for minTime you have "maxTime?: moment.Duration" .

Good luck !

**Comment by Dekminoz** [comment]
you have to import like this :   

`import * as moment from 'moment';`

**Comment by churro90** [comment]
This worked! Thank you so much!

**Comment by Dekminoz** [comment]
you're welcome !
