### ISSUE TITLE
Events not showing when initialized in ngOnInit

### ISSUE THREAD

**Issue by mircowidmer** [Jamaks/ng-fullcalendar#91]
The following minimal example shows the problem, that events are only shown briefly before being wiped again:

```
import { Component, OnInit } from '@angular/core';
import { Options } from 'fullcalendar';

@Component({
  selector: 'app-root',
  template: `
    <a (click)="loadAgain()">loadAgain</a>
    <ng-fullcalendar [options]="calendarOptions"
                     [(eventsModel)]="events"></ng-fullcalendar>
  `
})
export class AppComponent implements OnInit {
  readonly calendarOptions: Options = {};

  events: any[] = [];

  ngOnInit(): void {
    this.loadAgain();
  }

  loadAgain(): void {
    this.events = [ { title: 'Long Event', start: '2018-05-22T13:30:00', end: '2018-05-22T15:30:00'} ];
  }
}
```

When I click on "load again" the events are shown correctly. Only if I try to load them initially within ngOnInit(), they are displayed very briefly.

https://media.giphy.com/media/4NrMrmWq3lKjegrh5B/giphy.gif

I added an example project to reproduce the issue: https://github.com/mircowidmer/ng-full-calendar-flickering-issue

**Comment by Jamaks** [comment]
You must load [events] bindings after (initialized) Output
