### ISSUE TITLE
using calendar inside bootstrap tabs

### ISSUE THREAD

**Issue by ramajd** [Jamaks/ng-fullcalendar#92]
it seems that calendar has issue with bootstrap 3.x tabs component, according to [this guide](https://fullcalendar.io/docs/render) in official fullcalendar docs, I try to call `render` method after changing to calendar tab. but calendar is not rendering correctly. 

```html
<ng-fullcalendar class="calendar" #ucCalendar 
      [(eventsModel)]="events" [options]="calendarOptions" 
      (select)="selectEvent($event)" (eventClick)="removeEvent($event)"></ng-fullcalendar>
```

and when tab renders I call following method: 
```ts
renderCalendar() {
    this.ucCalendar.fullCalendar('render');
}
```
and calendar show as following image: 
<img width="421" alt="screen shot 2018-05-25 at 15 30 21" src="https://user-images.githubusercontent.com/1487731/40542004-73db6a5a-6033-11e8-94fb-5442c2ade2e2.png">

but it has to be showed as following image: 
<img width="360" alt="screen shot 2018-05-25 at 15 51 57" src="https://user-images.githubusercontent.com/1487731/40542050-aa1ae726-6033-11e8-88b7-7f94e1a4563a.png">

**Comment by Jamaks** [comment]
It's problem fullcalendar please see https://github.com/fullcalendar/fullcalendar/issues?utf8=%E2%9C%93&q=bootstrap

**Comment by ramajd** [comment]
calling `render` method in original fullcalendar shows the calendar correctly. but here it seems that `render` doesn't work. 

However I used following workaround to fix this issue, maybe help others.

```ts
renderCalendar($event) {
        this.ucCalendar.fullCalendar('destroy');
        setTimeout(() => {
            this.ucCalendar.fullCalendar(this.calendarOptions);
        }, 100);
}
```
