### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by owenmecham** [Jamaks/ng-fullcalendar#98]
What are the plans for supporting Angular 6?

**Comment by Jamaks** [comment]
I do not have enough time for the project, I really want to update the project and I hope we will soon take it

**Comment by chaucachavez** [comment]
has an approximate time, to update the project to Angular 6. Thanks

**Comment by dorthrithil** [comment]
I'm really looking forward for this to be fixed. Are there any further plans for ng6 support?

**Comment by mtuzinskiy** [comment]
@Jamaks But you have a plans on doing this, don't you? That's the best Fullcalendar wrapper out there, please don't drop it :)

**Comment by Jamaks** [comment]
I'll have a weekend soon, and I'll edit all issue :)

**Comment by Jamaks** [comment]
@owenmecham @owenmecham @chaucachavez @dorthrithil @mtuzinskiy 
package support Angular 6 
see please demo 
https://github.com/Jamaks/ng-fullcalendar-demo

I update demo project to Angular 6.

**Comment by Jamaks** [comment]
And see prod mode https://jamaks.github.io/ng-fullcalendar-demo/dist/
